### ISSUE TITLE
what is the meaning of '$0' in the phoneme?

### ISSUE THREAD

**Issue by yushanyong** [aishell-foundation/DaCiDian#2]
A	$0 a
AI	$0 ai
AN	$0 an
ANG	$0 ang
AO	$0 ao
BA	b a
BAI	b ai
BAN	b an
BANG	b ang
BAO	b ao

**Comment by sailordiary** [comment]
It's called a "zero initial" (零声母).

**Comment by dophist** [comment]
sailordiary is right.
